### ISSUE TITLE
Make build conventions more idiomatic

### ISSUE THREAD

**Issue by johnrengelman** [danveloper/gradle-js#1]
Default file should be `gradle.js` instead of `build.js`. This would be more idiomatic to the rest of the 19 umptillion JS build tools.

**Comment by danveloper** [comment]
IT'S OPEN SOURCE WE ARE OPEN TO PULL REQUESTS G'LUCK

**Comment by danveloper** [comment]
UGH FINE I'LL DO IT

**Comment by danveloper** [comment]
closed via #3
